### ISSUE TITLE
Neue Version vom 20.06.2024 (XRechnung 3.0.2)

### ISSUE THREAD

**Issue by appldev** [jcthiele/xrechnung-visualization-codelist-resolve#1]
Ist es geplant, dieses Projekt auf die aktuelle Version vom 20.06.2024 anzupassen?
https://github.com/itplr-kosit/xrechnung-visualization/releases

**Comment by jcthiele** [comment]
Ist erfolgt. Neue Version basierend auf der Version vom 20.06.2024 steht bereit.

**Comment by appldev** [comment]
Danke!
